version: '3'
services:
  frontend:
    image: 'instagram-sample-frontend:latest'
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    image: 'instagram-sample-backend:latest'
    ports:
      - 8000:8000

networks:
  default:
